version: '3.7'

services:
  postgres:
    container_name: CoM_postgres
    image: postgres:12
    networks:
      - CoM-back
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: nestjs
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    links:
      - postgres:postgres
    container_name: CoM_pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - CoM-back

networks:
  CoM-back:
volumes:
  pgdata: